/**
 * Builds /knowledge/knowledge.md from content.ts — the ONLY source the
 * Q&A Worker is allowed to answer from. Includes knowledgeOnly items
 * (never rendered on the page) plus the narrated/public content, but
 * excludes narration fields themselves (tour copy, not reference facts).
 *
 * Run: npm run knowledge
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  intro,
  research,
  octave,
  layer1,
  projects,
  teaching,
  teachingIntro,
  perspective,
  recognition,
  skillsKnowledge,
  educationKnowledge,
  membershipsKnowledge,
  volunteeringKnowledge,
  retailExperienceKnowledge,
  footer,
} from "../src/content/content";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "../knowledge/knowledge.md");

function section(title: string, body: string): string {
  return `## ${title}\n\n${body.trim()}\n\n`;
}

function roleBlock(r: { title: string; company: string; dateRange: string; location: string; details: string[] }): string {
  const bullets = r.details.map((d) => `- ${d}`).join("\n");
  return `**${r.title}**, ${r.company} (${r.dateRange})\n${r.location}\n${bullets}`;
}

let md = `# Knowledge base for Rachel Cooray's portfolio Q&A\n\n`;
md += `Generated by scripts/export-knowledge.ts from src/content/content.ts. Do not edit by hand.\n\n`;

md += section(
  "About",
  `${intro.name} — ${intro.tagline}\n\n${intro.bio}`
);

md += section(
  "Research",
  research
    .map((r) => `**${r.title}**, ${r.venue}. ${r.highlight}`)
    .join("\n\n")
);

md += section(
  "OCTAVE (current and past roles)",
  octave.map(roleBlock).join("\n\n")
);

md += section(
  "Layer1 Studio",
  `${roleBlock(layer1)}\n\nStats: ${layer1.stats.clients} clients, ${layer1.stats.projects} projects delivered. Client categories (no client names given): ${layer1.clientCategories.join(", ")}.`
);

md += section(
  "Projects",
  projects
    .map((p) => `**${p.title}** (${p.role})\n${p.description}\nTech: ${p.tech.join(", ") || "n/a"}`)
    .join("\n\n")
);

md += section(
  "Teaching & Mentoring",
  `${teachingIntro}\n\n` + teaching.map((t) => roleBlock({ ...t, company: t.institution, location: t.summary })).join("\n\n")
);

md += section("Perspective — how Rachel thinks about AI", perspective.paragraphs.join("\n\n"));

md += section(
  "Awards and press",
  recognition.map((r) => `**${r.title}**, ${r.organization} (${r.year}) — ${r.summary}`).join("\n\n")
);

md += section(
  "Skills",
  skillsKnowledge.map((s) => `${s.category}: ${s.items.join(", ")}`).join("\n")
);

md += section(
  "Education",
  educationKnowledge.map((e) => roleBlock({ ...e, company: e.institution, location: e.summary })).join("\n\n")
);

md += section("Memberships", membershipsKnowledge.join(", "));

md += section(
  "Volunteering",
  volunteeringKnowledge
    .map((v) => `**${v.title}**, ${v.organization} (${v.dateRange})\n${v.details.join(" ")}`)
    .join("\n\n")
);

md += section(
  "Other work experience (retail / customer service)",
  retailExperienceKnowledge.map(roleBlock).join("\n\n")
);

md += section(
  "Other",
  `${footer.fictionLine.text}\nContact: ${footer.email}`
);

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, md, "utf-8");
console.log(`Wrote ${outPath} (${md.length} chars)`);
